import { NextRequest, NextResponse } from 'next/server'

const GITHUB_API = 'https://api.github.com'

interface AegisConfig {
  projectId: string
  apiKey: string
  rules: string[]
}

// Generate AEGIS SDK code based on framework
function generateSDKCode(framework: string, config: AegisConfig): Record<string, string> {
  const files: Record<string, string> = {}

  if (framework === 'nextjs') {
    // Next.js middleware
    files['middleware.ts'] = `// AEGIS Real-Time Protection
// Auto-generated by AEGIS Security Scanner
import { aegisMiddleware } from '@aegis/protect'

export const middleware = aegisMiddleware({
  projectId: '${config.projectId}',
  apiKey: process.env.AEGIS_API_KEY || '${config.apiKey}',
  rules: ${JSON.stringify(config.rules, null, 4)},
  onAttack: async (attack) => {
    // Log attacks to AEGIS dashboard
    console.log('[AEGIS] Attack blocked:', attack.type)
  }
})

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)']
}
`

    files['.env.local.aegis'] = `# AEGIS Security Configuration
AEGIS_API_KEY=${config.apiKey}
AEGIS_PROJECT_ID=${config.projectId}
`

  } else if (framework === 'express') {
    files['aegis.config.js'] = `// AEGIS Real-Time Protection
const { aegisProtect } = require('@aegis/protect')

module.exports = aegisProtect({
  projectId: '${config.projectId}',
  apiKey: process.env.AEGIS_API_KEY || '${config.apiKey}',
  rules: ${JSON.stringify(config.rules, null, 4)}
})
`

    files['aegis-setup.md'] = `# AEGIS Setup Instructions

Add this to your Express app:

\`\`\`javascript
const aegis = require('./aegis.config')
app.use(aegis.middleware())
\`\`\`
`
  }

  // Package.json addition
  files['aegis-package-add.json'] = JSON.stringify({
    dependencies: {
      '@aegis/protect': '^1.0.0'
    }
  }, null, 2)

  return files
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { action, repoUrl, accessToken, framework = 'nextjs' } = body

    if (!accessToken) {
      return NextResponse.json({ error: 'GitHub access token required' }, { status: 401 })
    }

    // Parse repo URL
    const repoMatch = repoUrl.match(/github\.com\/([^\/]+)\/([^\/\.]+)/)
    if (!repoMatch) {
      return NextResponse.json({ error: 'Invalid GitHub repo URL' }, { status: 400 })
    }
    const [, owner, repo] = repoMatch

    const headers = {
      'Authorization': `Bearer ${accessToken}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    }

    if (action === 'create-pr') {
      // Generate unique project ID and API key
      const projectId = `aegis_${Date.now().toString(36)}`
      const apiKey = `aegis_key_${Math.random().toString(36).substr(2, 24)}`

      const config: AegisConfig = {
        projectId,
        apiKey,
        rules: ['sql-injection', 'xss', 'csrf', 'ratelimit', 'path-traversal']
      }

      // 1. Get default branch
      const repoRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}`, { headers })
      if (!repoRes.ok) {
        const error = await repoRes.json()
        return NextResponse.json({ error: error.message || 'Failed to access repo' }, { status: repoRes.status })
      }
      const repoData = await repoRes.json()
      const defaultBranch = repoData.default_branch

      // 2. Get latest commit SHA
      const refRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`, { headers })
      if (!refRes.ok) {
        return NextResponse.json({ error: 'Failed to get branch ref' }, { status: 400 })
      }
      const refData = await refRes.json()
      const baseSha = refData.object.sha

      // 3. Create new branch
      const branchName = `aegis-protection-${Date.now()}`
      const createBranchRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/git/refs`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          ref: `refs/heads/${branchName}`,
          sha: baseSha
        })
      })

      if (!createBranchRes.ok) {
        const error = await createBranchRes.json()
        return NextResponse.json({ error: error.message || 'Failed to create branch' }, { status: 400 })
      }

      // 4. Add AEGIS files
      const sdkFiles = generateSDKCode(framework, config)
      
      for (const [filename, content] of Object.entries(sdkFiles)) {
        // Skip non-code files
        if (filename.endsWith('.md') || filename.endsWith('.json')) continue

        await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filename}`, {
          method: 'PUT',
          headers,
          body: JSON.stringify({
            message: `[AEGIS] Add ${filename} for real-time protection`,
            content: Buffer.from(content).toString('base64'),
            branch: branchName
          })
        })
      }

      // 5. Create Pull Request
      const prRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/pulls`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          title: '🛡️ [AEGIS] Add Real-Time Attack Protection',
          head: branchName,
          base: defaultBranch,
          body: `## AEGIS Security Protection

This PR adds real-time attack protection to your application.

### What's included:
- \`middleware.ts\` - AEGIS protection middleware
- Real-time attack detection & blocking
- Dashboard monitoring integration

### Protected against:
- SQL Injection
- Cross-Site Scripting (XSS)
- CSRF Attacks
- Rate Limiting / DDoS
- Path Traversal

### Setup:
1. Merge this PR
2. Run \`npm install @aegis/protect\`
3. Add \`AEGIS_API_KEY=${apiKey}\` to your \`.env\`
4. Deploy your app

### Monitor attacks:
Visit your [AEGIS Dashboard](https://aegis.security/dashboard) to monitor real-time attacks.

---
*Generated by [AEGIS Security Scanner](https://aegis.security)*`
        })
      })

      if (!prRes.ok) {
        const error = await prRes.json()
        return NextResponse.json({ error: error.message || 'Failed to create PR' }, { status: 400 })
      }

      const prData = await prRes.json()

      return NextResponse.json({
        success: true,
        pr: {
          url: prData.html_url,
          number: prData.number,
          title: prData.title
        },
        config: {
          projectId,
          apiKey,
          dashboardUrl: `https://aegis.security/dashboard/${projectId}`
        }
      })
    }

    if (action === 'check-access') {
      // Check if we have write access to repo
      const res = await fetch(`${GITHUB_API}/repos/${owner}/${repo}`, { headers })
      if (!res.ok) {
        return NextResponse.json({ hasAccess: false, error: 'Cannot access repo' })
      }
      const data = await res.json()
      return NextResponse.json({
        hasAccess: data.permissions?.push || false,
        repo: {
          name: data.full_name,
          defaultBranch: data.default_branch,
          private: data.private
        }
      })
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

export async function GET() {
  return NextResponse.json({
    endpoints: {
      'POST /api/github/pr': {
        actions: ['create-pr', 'check-access'],
        required: ['repoUrl', 'accessToken']
      }
    }
  })
}
